
target_sources(hikogui PRIVATE
    ${HIKOGUI_SOURCE_DIR}/concurrency/dead_lock_detector_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/concurrency/thread_impl.cpp
    $<$<PLATFORM_ID:Darwin>:${HIKOGUI_SOURCE_DIR}/concurrency/thread_macos_impl.cpp>
    $<$<PLATFORM_ID:Windows>:${HIKOGUI_SOURCE_DIR}/concurrency/thread_win32_impl.cpp>
    ${HIKOGUI_SOURCE_DIR}/font/font_book_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/font/font_impl.cpp
    #${HIKOGUI_SOURCE_DIR}/font/true_type_font_coverage_impl.cpp
    #${HIKOGUI_SOURCE_DIR}/font/true_type_font_GSUB_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/font/true_type_font_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/geometry/axis_aligned_rectangle_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/GUI/gui_system_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/GUI/gui_system_win32_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/GUI/gui_window_impl.cpp
    $<$<PLATFORM_ID:Windows>:${HIKOGUI_SOURCE_DIR}/GUI/gui_window_win32_impl.cpp>
    ${HIKOGUI_SOURCE_DIR}/GUI/keyboard_bindings_impl.cpp
    $<$<PLATFORM_ID:Windows>:${HIKOGUI_SOURCE_DIR}/GUI/keyboard_virtual_key_win32_impl.cpp>
    ${HIKOGUI_SOURCE_DIR}/GUI/widget_draw_context_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/i18n/iso_3166_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/i18n/iso_15924_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/i18n/language_tag_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/l10n/po_parser_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/l10n/translation_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/theme/theme_file_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/unicode/grapheme_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/unicode/gstring_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/unicode/ucd_compositions.hpp
    ${HIKOGUI_SOURCE_DIR}/unicode/ucd_decompositions.hpp
    ${HIKOGUI_SOURCE_DIR}/unicode/ucd_descriptions.hpp
    ${HIKOGUI_SOURCE_DIR}/unicode/ucd_index.hpp
    ${HIKOGUI_SOURCE_DIR}/unicode/unicode_bidi_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/unicode/unicode_description_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/unicode/unicode_normalization_impl.cpp
    ${HIKOGUI_SOURCE_DIR}/unicode/unicode_text_segmentation_impl.cpp
    $<$<PLATFORM_ID:Windows>:${HIKOGUI_SOURCE_DIR}/utility/debugger_win32_impl.cpp>
    $<$<PLATFORM_ID:Windows>:${HIKOGUI_SOURCE_DIR}/utility/exception_win32_impl.cpp>
)
