
if(VCPKG_CHAINLOAD_TOOLCHAIN_FILE)
    # vcpkg does not allow absolute paths anywhere in the install directory.
    # These directories are normally used to execute files in their build
    # directory; which does not happen on a vcpkg install.
    set(LIBRARY_SOURCE_DIR "vcpkg_no_source_dir")
    set(LIBRARY_BUILD_DIR "vcpkg_no_build_dir")
else()
    set(LIBRARY_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    set(LIBRARY_BUILD_DIR "${CMAKE_CURRENT_BINARY_DIR}")
endif()

configure_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/metadata/library_metadata.hpp.in
    ${CMAKE_CURRENT_BINARY_DIR}/src/hikogui/metadata/library_metadata.hpp @ONLY)

target_sources(hikogui INTERFACE FILE_SET hikogui_generated_include_files TYPE HEADERS BASE_DIRS "${CMAKE_CURRENT_BINARY_DIR}/src/" FILES
    ${CMAKE_CURRENT_BINARY_DIR}/src/hikogui/metadata/library_metadata.hpp
)

target_sources(hikogui INTERFACE FILE_SET hikogui_include_files TYPE HEADERS BASE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/src/"  FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_block.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_channel.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_device.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_device_asio.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_device_delegate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_device_state.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_device_win32.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_direction.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_format_range.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_sample_format.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_sample_packer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_sample_unpacker.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_stream_config.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_stream_format.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_stream_format_win32.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_system.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_system_aggregate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_system_asio.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio_system_win32.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/audio.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/pcm_format.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/speaker_mapping.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/speaker_mapping_win32.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/surround_mode.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/win32_device_interface.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/audio/win32_wave_device.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/algorithm/algorithm.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/algorithm/animator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/algorithm/algorithm_misc.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/algorithm/ranges.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/algorithm/recursive_iterator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/algorithm/strings.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/ascii.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/char_converter.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/cp_1252.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/iso_8859_1.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/char_maps.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/random_char.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/to_string.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/utf_16.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/utf_32.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/char_maps/utf_8.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/base_n.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/BON8.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/datum.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/gzip.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/huffman.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/indent.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/inflate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/JSON.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/jsonpath.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/codec.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/pickle.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/png.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/SHA2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/codec/zlib.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/color/color.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/color/color_space.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/color/color_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/color/quad_color.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/color/Rec2020.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/color/Rec2100.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/color/semantic_color.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/color/sRGB.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/atomic.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/callback.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/callback_flags.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/global_state.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/id_factory.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/concurrency.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/rcu.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/subsystem.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/thread.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/thread_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/thread_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/unfair_mutex.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/unfair_mutex_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/unfair_mutex_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/unfair_recursive_mutex.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/concurrency/wfree_idle_count.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/byte_string.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/function_fifo.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/functional.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/lean_vector.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/container.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/polymorphic_optional.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/secure_vector.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/small_map.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/small_vector.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/stable_set.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/stack.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/tree.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/undo_stack.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/vector_span.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/void_span.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/wfree_fifo.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/container/wfree_unordered_map.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/coroutine/awaitable.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/coroutine/generator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/coroutine/coroutine.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/coroutine/task.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/crt/crt.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/crt/crt_utils.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/crt/crt_utils_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/crt/crt_utils_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/awaitable_timer_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/awaitable_timer_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/dispatch.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/function_timer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/loop_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/loop_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/notifier.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/scoped_task.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/socket_event.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/socket_event_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/socket_event_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/dispatch/when_any.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/access_mode.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/file_intf.hpp
    $<$<PLATFORM_ID:Linux>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/file_posix_impl.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/file_win32_impl.hpp>
    $<$<PLATFORM_ID:Linux>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/file_view_posix_impl.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/file_view_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/file_view.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/file.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/resource_view.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/file/seek_whence.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/elusive_icon.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font_book.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font_char_map.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font_family_id.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font_metrics.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font_variant.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font_weight.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/glyph_atlas_info.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/glyph_id.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/glyph_metrics.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/hikogui_icon.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font_font.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/font_style.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_cmap.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_glyf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_head.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_hhea.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_hmtx.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_kern.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_loca.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_maxp.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_name.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_os2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_sfnt.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/otype_utilities.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/font/true_type_font.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_add_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_arguments.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_assign_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_binary_operator_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_bit_and_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_bit_or_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_bit_xor_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_call_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_decrement_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_div_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_eq_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_evaluation_context.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_filter_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_ge_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_gt_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_increment_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_index_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_add_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_and_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_div_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_mod_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_mul_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_or_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_shl_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_shr_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_sub_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_inplace_xor_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_invert_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_le_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_literal_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_logical_and_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_logical_not_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_logical_or_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_lt_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_map_literal_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_member_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_minus_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_mod_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_mul_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_name_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_ne_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_parser.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_plus_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_post_process_context.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_pow_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_shl_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_shr_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_sub_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_ternary_operator_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_unary_operator_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula_vector_literal_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/formula/formula.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/draw_context_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/draw_context_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_device_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_device_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_queue_vulkan.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_surface_delegate_vulkan.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_surface_state.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_surface_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_surface_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_system_globals.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_system_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_system_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/GFX.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_override_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_override_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_box_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_box_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_image_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_image_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_SDF_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_SDF_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_tone_mapper_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_tone_mapper_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_vulkan_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/gfx_pipeline_vulkan_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/render_doc.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GFX/renderdoc_app.h
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/gui_event.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/gui_event_type.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/gui_event_variant.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/gui_window_size.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/gui_window_win32.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/hitbox.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/keyboard_bindings.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/keyboard_focus_direction.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/keyboard_focus_group.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/keyboard_key.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/keyboard_modifiers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/keyboard_state.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/keyboard_virtual_key_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/keyboard_virtual_key_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/GUI.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/mouse_buttons.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/mouse_cursor.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/theme.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/theme_book.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/widget_id.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/widget_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/GUI/widget_layout.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/aarectangle.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/alignment.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/axis.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/circle.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/corner_radii.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/extent2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/extent3.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/line_end_cap.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/line_join_style.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/line_segment.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/lookat.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/margins.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/matrix2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/matrix3.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/geometry.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/perspective.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/point2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/point3.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/quad.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/rectangle.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/rotate2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/rotate3.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/scale2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/scale3.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/transform.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/translate2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/translate3.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/vector2.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/geometry/vector3.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/graphic_path/bezier.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/graphic_path/bezier_curve.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/graphic_path/bezier_point.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/graphic_path/graphic_path.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/graphic_path/graphic_path.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/iso_15924.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/iso_15924_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/iso_15924_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/iso_3166.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/iso_3166_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/iso_3166_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/iso_639.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/language_tag.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/language_tag_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/language_tag_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/i18n/i18n.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/image.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/pixmap.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/pixmap_span.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/sdf_r8.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/sfloat_rg32.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/sfloat_rgb32.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/sfloat_rgba16.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/sfloat_rgba32.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/sfloat_rgba32x4.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/sint_abgr8_pack.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/snorm_r8.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/srgb_abgr8_pack.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/uint_abgr8_pack.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/image/unorm_a2bgr10_pack.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/l10n/label.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/l10n/l10n.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/l10n/po_parser.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/l10n/po_translations.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/l10n/txt.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/l10n/translation.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/layout/box_constraints.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/layout/box_shape.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/layout/grid_layout.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/layout/layout.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/layout/row_column_layout.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/layout/spreadsheet_address.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/memory/locked_memory_allocator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/memory/locked_memory_allocator_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/memory/locked_memory_allocator_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/memory/memory.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/memory/secure_memory_allocator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/metadata/application_metadata.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/metadata/metadata.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/metadata/semantic_version.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/net/net.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/net/packet.hpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/net/packet_buffer.hpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/net/stream.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/bigint.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/bound_integer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/decimal.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/fixed.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/interval.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/int_carry.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/int_overflow.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/numeric.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/polynomial.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/numeric/safe_int.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/observer/group_ptr.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/observer/observer_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/observer/observed.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/observer/observed_value.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/observer/observer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/observer/shared_state.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/parser/lexer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/parser/lookahead_iterator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/parser/operator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/parser/parse_location.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/parser/parser.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/parser/placement.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/parser/token.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/path/glob.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/path/path.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/path/path_location.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/path/path_location_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/path/path_location_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/path/URI.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/path/URL.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/random/dither.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/random/random.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/random/seed.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/random/seed_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/random/seed_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/random/xorshift128p.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/float16_sse4_1.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/SIMD.hpp
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_f16x8_sse2.hpp>
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_f32x4_sse.hpp>
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_f64x4_avx.hpp>
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_i16x8_sse2.hpp>
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_i32x4_sse2.hpp>
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_i64x4_avx2.hpp>
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_i8x16_sse2.hpp>
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_simd_conversions_x86.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_simd_utility.hpp
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/native_u32x4_sse2.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/SIMD/simd_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/security/security.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/security/security_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/security/security_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/security/sip_hash.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/settings.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/os_settings.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/os_settings_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/os_settings_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/preferences.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/theme_mode.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/subpixel_orientation.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/user_settings.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/user_settings_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/settings/user_settings_win32_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/parser.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_block_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_break_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_continue_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_do_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_expression_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_for_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_function_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_if_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_parse_context.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_placeholder_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_return_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_string_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_top_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/skeleton/skeleton_while_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/telemetry/counters.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/telemetry/delayed_format.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/telemetry/format_check.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/telemetry/log.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/telemetry/telemetry.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/telemetry/trace.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/text.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/semantic_text_style.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/text_cursor.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/text_decoration.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/text_selection.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/text_shaper.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/text_shaper_char.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/text_shaper_line.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/text/text_style.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/time/chrono.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/time/time.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/time/time_stamp_count.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/time/time_stamp_utc.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/grapheme.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/gstring.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/markup.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/phrasing.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_bidi_classes.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_bidi_mirroring_glyphs.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_bidi_paired_bracket_types.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_canonical_combining_classes.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_compositions.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_decompositions.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_east_asian_widths.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_general_categories.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_grapheme_cluster_breaks.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_lexical_classes.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_line_break_classes.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_scripts.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_sentence_break_properties.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/ucd_word_break_properties.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_bidi.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_break_opportunity.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_description.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_grapheme_cluster_break.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_line_break.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_normalization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_plural.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_sentence_break.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/unicode/unicode_word_break.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/architecture.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/assert.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/bits.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/cast.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/charconv.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/compare.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/concepts.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/console_win32.hpp>
    $<$<STREQUAL:${ARCHITECTURE_ID},x86>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/cpu_id_x86.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/debugger_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/debugger_utils.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/debugger_win32_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/debugger.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/defer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/dialog_intf.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/dialog_win32_impl.hpp>
    $<$<PLATFORM_ID:MacOS>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/dialog_maxos_impl.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/dialog.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/endian.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/enum_metadata.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/exception_intf.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/exception_win32_impl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/exception.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/fixed_string.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/half.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/float_to_half.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/half_to_float.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/forward_value.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/hash.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/initialize.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/math.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/memory.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/misc.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/utility.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/not_null.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/numbers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/policy.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/reflection.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/tagged_id.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/terminate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/time_zone.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/type_traits.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/units.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/utility/value_traits.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/abstract_button_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/audio_device_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/button_delegate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/checkbox_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/grid_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/icon_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/label_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/menu_button_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/widgets.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/momentary_button_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/overlay_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/radio_button_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/scroll_aperture_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/scroll_bar_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/scroll_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/selection_delegate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/selection_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/spacer_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/system_menu_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/tab_delegate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/tab_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/text_delegate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/text_field_delegate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/text_field_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/text_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/toggle_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/toolbar_button_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/toolbar_tab_button_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/toolbar_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/widget_mode.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/window_controls_macos_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/window_controls_win32_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/window_widget.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/widgets/with_label_widget.hpp
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32/base.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32/libloaderapi.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32/processthreadsapi.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32/synchapi.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32/win32.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32/winnls.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32/winreg.hpp>
    $<$<PLATFORM_ID:Windows>:${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32/winuser.hpp>
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/macros.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/crt.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/hikogui.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/test.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/hikogui/win32_headers.hpp
)
