
from .psp import psp_execute
from .deduplicate import deduplicate
from .bits_as_bytes import bits_as_bytes
import sys

def generate_scripts(template_path, output_path, descriptions):
    print("Processing scripts:", file=sys.stderr, flush=True)

    script_enum = {
        "Adlam": 166,
        "Ahom": 338,
        "Anatolian_Hieroglyphs": 80,
        "Arabic": 160,
        "Armenian": 230,
        "Avestan": 134,
        "Balinese": 360,
        "Bamum": 435,
        "Bassa_Vah": 259,
        "Batak": 365,
        "Bengali": 325,
        "Bhaiksuki": 334,
        "Bopomofo": 285,
        "Brahmi": 300,
        "Braille": 570,
        "Buginese": 367,
        "Buhid": 372,
        "Canadian_Aboriginal": 440,
        "Carian": 201,
        "Caucasian_Albanian": 239,
        "Chakma": 349,
        "Cham": 358,
        "Cherokee": 445,
        "Chorasmian": 109,
        "Common": 994, # iso-15924{"Zinh"} Inherited
        "Coptic": 204,
        "Cuneiform": 20,
        "Cypriot": 403,
        "Cypro_Minoan": 402,
        "Cyrillic": 220,
        "Deseret": 250,
        "Devanagari": 315,
        "Dives_Akuru": 342,
        "Dogra": 328,
        "Duployan": 755,
        "Egyptian_Hieroglyphs": 50,
        "Elbasan": 226,
        "Elymaic": 128,
        "Ethiopic": 430,
        "Georgian": 240,
        "Glagolitic": 225,
        "Gothic": 206,
        "Grantha": 343,
        "Greek": 200,
        "Gujarati": 320,
        "Gunjala_Gondi": 312,
        "Gurmukhi": 310,
        "Han": 500,
        "Hangul": 286,
        "Hanifi_Rohingya": 167,
        "Hanunoo": 371,
        "Hatran": 127,
        "Hebrew": 125,
        "Hiragana": 410,
        "Imperial_Aramaic": 124,
        "Inherited": 994,
        "Inscriptional_Pahlavi": 131,
        "Inscriptional_Parthian": 130,
        "Javanese": 361,
        "Kaithi": 317,
        "Kannada": 345,
        "Katakana": 411,
        "Kawi": 368,
        "Kayah_Li": 357,
        "Kharoshthi": 305,
        "Khitan_Small_Script": 288,
        "Khmer": 355,
        "Khojki": 322,
        "Khudawadi": 318,
        "Lao": 356,
        "Latin": 215,
        "Lepcha": 335,
        "Limbu": 336,
        "Linear_A": 400,
        "Linear_B": 401,
        "Lisu": 399,
        "Lycian": 202,
        "Lydian": 116,
        "Mahajani": 314,
        "Makasar": 366,
        "Malayalam": 347,
        "Mandaic": 140,
        "Manichaean": 139,
        "Marchen": 332,
        "Masaram_Gondi": 313,
        "Medefaidrin": 265,
        "Meetei_Mayek": 337,
        "Mende_Kikakui": 438,
        "Meroitic_Cursive": 101,
        "Meroitic_Hieroglyphs": 100,
        "Miao": 282,
        "Modi": 324,
        "Mongolian": 145,
        "Mro": 264,
        "Multani": 323,
        "Myanmar": 350,
        "Nabataean": 159,
        "Nag_Mundari": 295,
        "Nandinagari": 311,
        "New_Tai_Lue": 354,
        "Newa": 333,
        "Nko": 165,
        "Nushu": 499,
        "Nyiakeng_Puachue_Hmong": 451,
        "Ogham": 212,
        "Ol_Chiki": 261,
        "Old_Hungarian": 176,
        "Old_Italic": 210,
        "Old_North_Arabian": 106,
        "Old_Permic": 227,
        "Old_Persian": 30,
        "Old_Sogdian": 142,
        "Old_South_Arabian": 105,
        "Old_Turkic": 175,
        "Old_Uyghur": 143,
        "Oriya": 327,
        "Osage": 219,
        "Osmanya": 260,
        "Pahawh_Hmong": 450,
        "Palmyrene": 126,
        "Pau_Cin_Hau": 263,
        "Phags_Pa": 331,
        "Phoenician": 115,
        "Psalter_Pahlavi": 132,
        "Rejang": 363,
        "Runic": 211,
        "Samaritan": 123,
        "Saurashtra": 344,
        "Sharada": 319,
        "Shavian": 281,
        "Siddham": 302,
        "SignWriting": 95,
        "Sinhala": 348,
        "Sogdian": 141,
        "Sora_Sompeng": 398,
        "Soyombo": 329,
        "Sundanese": 362,
        "Syloti_Nagri": 316,
        "Syriac": 135,
        "Tagalog": 370,
        "Tagbanwa": 373,
        "Tai_Le": 353,
        "Tai_Tham": 351,
        "Tai_Viet": 359,
        "Takri": 321,
        "Tamil": 346,
        "Tangsa": 275,
        "Tangsa": 520,
        "Tangut": 520,
        "Telugu": 340,
        "Thaana": 170,
        "Thai": 352,
        "Tibetan": 330,
        "Tifinagh": 120,
        "Tirhuta": 326,
        "Toto": 294,
        "Ugaritic": 40,
        "Vai": 470,
        "Vithkuqi": 228,
        "Wancho": 283,
        "Warang_Citi": 262,
        "Yezidi": 192,
        "Yi": 460,
        "Zanabazar_Square": 339,
        "Zzzz": 0,
    }

    used_scripts = set(x.script for x in descriptions)
    unused_scripts = script_enum.keys() - used_scripts
    for unused_script in sorted(unused_scripts):
        print("    unused script:", unused_script, file=sys.stderr)

    scripts = [script_enum[x.script] for x in descriptions]

    scripts, indices, chunk_size = deduplicate(scripts)
    scripts_bytes, script_width = bits_as_bytes(scripts)
    indices_bytes, index_width = bits_as_bytes(indices)

    print("    chunk-size={} #indices={}:{} #scripts={}:{} total={} bytes".format(
        chunk_size,
        len(indices), index_width,
        len(scripts), script_width,
        len(indices_bytes) + len(scripts_bytes)),
        file=sys.stderr)

    psp_execute(
        template_path,
        output_path,
        chunk_size=chunk_size,
        indices_size=len(indices),
        index_width=index_width,
        indices_bytes=indices_bytes,
        script_enum=script_enum,
        script_width=script_width,
        scripts_bytes=scripts_bytes
    )
