name: Protect Main
on:
  push:
    branches:
      - main
jobs:
  check-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Source must not contain Debug code (#if 1)
        run: |
          if grep -q -r '#if 1' --include="*.hpp" .; then
            echo "Debugging code found in .hpp files. Please remove it before pushing."
            exit 1
          fi